# Generated by Django 5.1 on 2024-09-16 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='events/')),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=300)),
                ('description', models.TextField(null=True)),
                ('organizer', models.CharField(max_length=300)),
                ('capacity', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('prizes', models.JSONField(default=list)),
                ('sponsors', models.JSONField(default=list)),
                ('event_handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
