# Generated by Django 5.1 on 2024-09-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='prizes',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='sponsors',
            field=models.CharField(max_length=700),
        ),
    ]
