# Generated by Django 5.1 on 2024-09-17 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_prizes_alter_event_sponsors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=300)),
                ('persons_required', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='rooms/')),
                ('room_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
