# Generated by Django 5.1.1 on 2024-09-12 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='community/images')),
                ('socials', models.JSONField(blank=True, default=list, verbose_name=models.URLField())),
                ('messages', models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=500))),
                ('members', models.ManyToManyField(related_name='communityMembers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
