# Generated by Django 5.1.1 on 2024-09-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_community_messages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='socials',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name=models.URLField()),
        ),
    ]
